import crypto from 'crypto';
import {
  User,
  ActivityEvent,
  WorkflowCandidate,
  Workflow,
  WorkflowStep,
  Integration,
  Automation,
  Execution,
  ExecutionStep,
  Notification,
  UserSetting,
} from '../shared/types.js';

export function hashPassword(password: string): string {
  return crypto.createHash('sha256').update(password).digest('hex');
}

export const DEMO_USER_ID = 'usr_workflowos_demo_01';
export const DEMO_USER: User = {
  id: DEMO_USER_ID,
  email: 'demo@workflowos.ai',
  passwordHash: hashPassword('demo123'),
  name: 'Sarah Chen',
  role: 'ADMIN',
  avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
  createdAt: '2026-09-01T08:00:00.000Z',
  updatedAt: '2026-09-25T12:00:00.000Z',
};

export const INITIAL_USER_SETTINGS: UserSetting = {
  id: 'set_01',
  userId: DEMO_USER_ID,
  activityMonitoringEnabled: true,
  aiDiscoveryEnabled: true,
  autoSuggestionsEnabled: true,
  requireApprovalDefault: true,
  sensitiveDataFilterEnabled: true,
  excludedApps: ['Banking', 'Password Managers', 'Authentication Apps', 'Private Messaging', '1Password', 'Bitwarden'],
  retentionDays: 90,
  aiModelPreference: 'gemini-2.5-flash',
};

export const INITIAL_INTEGRATIONS: Integration[] = [
  {
    id: 'int_gmail',
    userId: DEMO_USER_ID,
    type: 'GMAIL',
    name: 'Google Workspace Mail',
    application: 'Gmail',
    status: 'CONNECTED',
    config: { account: 'sarah.chen@enterprise.com', scopes: ['mail.read', 'mail.modify'] },
    lastTestedAt: '2026-09-25T14:30:00.000Z',
    authType: 'OAUTH2',
    latencyMs: 142,
  },
  {
    id: 'int_slack',
    userId: DEMO_USER_ID,
    type: 'SLACK',
    name: 'Production Slack Workspace',
    application: 'Slack',
    status: 'CONNECTED',
    config: { workspace: 'Enterprise HQ', defaultChannel: '#customer-operations' },
    lastTestedAt: '2026-09-25T15:00:00.000Z',
    authType: 'OAUTH2',
    latencyMs: 98,
  },
  {
    id: 'int_crm',
    userId: DEMO_USER_ID,
    type: 'CRM',
    name: 'HubSpot Enterprise CRM',
    application: 'HubSpot CRM',
    status: 'CONNECTED',
    config: { portalId: '9841203', endpoint: 'https://api.hubspot.com/v3' },
    lastTestedAt: '2026-09-25T16:15:00.000Z',
    authType: 'API_KEY',
    latencyMs: 230,
  },
  {
    id: 'int_sheets',
    userId: DEMO_USER_ID,
    type: 'SHEETS',
    name: 'Google Sheets Financial Records',
    application: 'Google Sheets',
    status: 'CONNECTED',
    config: { spreadsheetId: '1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms' },
    lastTestedAt: '2026-09-25T13:45:00.000Z',
    authType: 'OAUTH2',
    latencyMs: 180,
  },
  {
    id: 'int_browser',
    userId: DEMO_USER_ID,
    type: 'BROWSER',
    name: 'Chromium Playwright Automation Engine',
    application: 'Chrome',
    status: 'CONNECTED',
    config: { headless: true, stealthMode: true, viewport: { width: 1440, height: 900 } },
    lastTestedAt: '2026-09-25T18:00:00.000Z',
    authType: 'SIMULATED_MOCK',
    latencyMs: 64,
  },
];

export const INITIAL_CANDIDATES: WorkflowCandidate[] = [
  {
    id: 'cand_cust_req',
    userId: DEMO_USER_ID,
    name: 'Process Customer Request',
    intent: 'Extract customer issue from Gmail email, verify account in CRM, update account state, and notify operations in Slack.',
    applications: ['Gmail', 'Chrome', 'HubSpot CRM', 'Slack'],
    frequency: 14,
    similarity: 0.94,
    crossAppTransitions: 4,
    avgDurationSecs: 384,
    confidenceScore: 0.92,
    estimatedWeeklyTimeSavedSecs: 5376, // ~89 mins/week
    status: 'ACCEPTED',
    discoveredAt: '2026-09-24T09:15:00.000Z',
    reviewedAt: '2026-09-24T10:00:00.000Z',
    suggestedTrigger: 'New inbound email with label [Customer Support]',
    suggestedStepsCount: 5,
    potentialRisks: ['Customer not found in CRM may require human intervention'],
    rawSequence: [
      { app: 'Gmail', action: 'Open customer email', eventType: 'EMAIL_OPENED', target: 'Subject: Urgent Inquiry' },
      { app: 'Gmail', action: 'Download statement PDF', eventType: 'EMAIL_ATTACHMENT_DOWNLOADED', target: 'statement_sep.pdf' },
      { app: 'HubSpot CRM', action: 'Search customer record', eventType: 'CRM_RECORD_SEARCHED', target: 'Search by Email' },
      { app: 'HubSpot CRM', action: 'Update ticket status to Processing', eventType: 'CRM_RECORD_UPDATED', target: 'Ticket #4910' },
      { app: 'Slack', action: 'Post update in #customer-ops', eventType: 'MESSAGE_SENT', target: '#customer-ops' },
    ],
  },
  {
    id: 'cand_invoice_sync',
    userId: DEMO_USER_ID,
    name: 'Weekly Invoice Spreadsheet Sync',
    intent: 'Extract downloaded billing CSVs from Chrome, parse rows, and insert synchronized accounting records into Google Sheets.',
    applications: ['Chrome', 'Desktop Files', 'Google Sheets'],
    frequency: 8,
    similarity: 0.91,
    crossAppTransitions: 3,
    avgDurationSecs: 420,
    confidenceScore: 0.88,
    estimatedWeeklyTimeSavedSecs: 3360,
    status: 'DISCOVERED',
    discoveredAt: '2026-09-25T11:20:00.000Z',
    suggestedTrigger: 'CSV file downloaded matching "invoice_export_*.csv"',
    suggestedStepsCount: 4,
    potentialRisks: ['Header schema change in accounting export'],
    rawSequence: [
      { app: 'Chrome', action: 'Export payment report CSV', eventType: 'DATA_EXPORTED', target: 'Stripe Billing Portal' },
      { app: 'Desktop Files', action: 'Read downloaded CSV', eventType: 'FILE_CREATED', target: 'invoice_export_2026_09.csv' },
      { app: 'Google Sheets', action: 'Append row to Q3 Ledger', eventType: 'SPREADSHEET_ROW_ADDED', target: 'Financial Ledger' },
    ],
  },
  {
    id: 'cand_lead_notify',
    userId: DEMO_USER_ID,
    name: 'New Lead Ingestion & Dispatch',
    intent: 'Detect new webform submissions in CRM, qualify lead score, and broadcast instantaneous high-priority lead card to sales Slack channel.',
    applications: ['HubSpot CRM', 'Slack'],
    frequency: 19,
    similarity: 0.96,
    crossAppTransitions: 2,
    avgDurationSecs: 180,
    confidenceScore: 0.95,
    estimatedWeeklyTimeSavedSecs: 3420,
    status: 'ACCEPTED',
    discoveredAt: '2026-09-23T14:40:00.000Z',
    reviewedAt: '2026-09-23T15:10:00.000Z',
    suggestedTrigger: 'CRM Lead created with lifecycle stage = "MQL"',
    suggestedStepsCount: 3,
    potentialRisks: ['Rate limits on rapid inbound web traffic bursts'],
    rawSequence: [
      { app: 'HubSpot CRM', action: 'Filter high score leads', eventType: 'CRM_RECORD_SEARCHED', target: 'MQL Filter' },
      { app: 'HubSpot CRM', action: 'Assign owner to SDR Team', eventType: 'CRM_RECORD_UPDATED', target: 'Lead Contact' },
      { app: 'Slack', action: 'Broadcast lead card with quick links', eventType: 'MESSAGE_SENT', target: '#sales-leads' },
    ],
  },
  {
    id: 'cand_refund_triage',
    userId: DEMO_USER_ID,
    name: 'Customer Refund Triage & Compliance Check',
    intent: 'Capture refund request tickets, query payment gateway history via browser automation, and initiate refund approval.',
    applications: ['Gmail', 'Chrome', 'HubSpot CRM', 'Slack'],
    frequency: 6,
    similarity: 0.85,
    crossAppTransitions: 4,
    avgDurationSecs: 510,
    confidenceScore: 0.84,
    estimatedWeeklyTimeSavedSecs: 3060,
    status: 'REVIEWING',
    discoveredAt: '2026-09-25T16:00:00.000Z',
    suggestedTrigger: 'Email with subject containing "Refund Request"',
    suggestedStepsCount: 5,
    potentialRisks: ['Financial transaction approval requires strict human oversight'],
    rawSequence: [
      { app: 'Gmail', action: 'Open refund email', eventType: 'EMAIL_OPENED', target: 'Refund Inquiry' },
      { app: 'Chrome', action: 'Lookup charge ID in payment terminal', eventType: 'BROWSER_NAVIGATION', target: 'Payment Gateway' },
      { app: 'HubSpot CRM', action: 'Flag account as Pending Refund', eventType: 'CRM_RECORD_UPDATED', target: 'Customer Status' },
      { app: 'Slack', action: 'Notify #finance-approvals', eventType: 'MESSAGE_SENT', target: '#finance-approvals' },
    ],
  },
];

export const INITIAL_WORKFLOWS: Workflow[] = [
  {
    id: 'wf_process_cust_req',
    userId: DEMO_USER_ID,
    candidateId: 'cand_cust_req',
    name: 'Process Customer Request',
    description: 'Autonomous customer request handling: parses inbound email, downloads attachment, synchronizes CRM record, and alerts team on Slack.',
    category: 'Customer Operations',
    version: 1,
    status: 'ACTIVE',
    createdAt: '2026-09-24T10:15:00.000Z',
    updatedAt: '2026-09-25T17:00:00.000Z',
    lastRunAt: '2026-09-25T21:40:00.000Z',
    totalExecutions: 16,
    successRate: 93.75,
    trigger: {
      id: 'trig_01',
      type: 'EMAIL_RECEIVED',
      application: 'Gmail',
      description: 'Trigger when new customer support email arrives',
      config: { query: 'label:support newer_than:1d' },
    },
    variables: [
      { name: 'customerEmail', type: 'string', defaultValue: 'customer@acmecorp.com' },
      { name: 'ticketSubject', type: 'string', defaultValue: 'Need assistance with enterprise tier' },
      { name: 'priority', type: 'string', defaultValue: 'HIGH' },
    ],
    conditions: [
      { id: 'cond_cust_01', field: 'customerFound', operator: 'EQUALS', value: true },
    ],
    steps: [
      {
        id: 'step_1',
        stepIndex: 1,
        name: 'Extract Customer Information',
        type: 'ACTION',
        application: 'Gmail',
        actionType: 'PARSE_EMAIL_METADATA',
        parameters: { extractFields: ['sender', 'subject', 'body', 'attachmentNames'] },
        executionMethod: 'API',
        timeoutMs: 15000,
      },
      {
        id: 'step_2',
        stepIndex: 2,
        name: 'Download & Scan Attachment',
        type: 'ACTION',
        application: 'Gmail',
        actionType: 'DOWNLOAD_ATTACHMENTS',
        parameters: { maxFiles: 3, allowedExtensions: ['.pdf', '.png', '.docx'] },
        executionMethod: 'API',
        timeoutMs: 25000,
      },
      {
        id: 'step_3',
        stepIndex: 3,
        name: 'Search Customer in HubSpot CRM',
        type: 'ACTION',
        application: 'HubSpot CRM',
        actionType: 'SEARCH_CONTACT',
        parameters: { searchBy: 'email', fallbackCreate: true },
        executionMethod: 'API',
        timeoutMs: 20000,
      },
      {
        id: 'step_4',
        stepIndex: 4,
        name: 'Verify Account Active Status',
        type: 'CONDITION',
        application: 'HubSpot CRM',
        actionType: 'EVALUATE_CONDITION',
        parameters: { field: 'status', expected: 'ACTIVE' },
        executionMethod: 'API',
        timeoutMs: 5000,
      },
      {
        id: 'step_5',
        stepIndex: 5,
        name: 'Update Customer Ticket Details',
        type: 'ACTION',
        application: 'HubSpot CRM',
        actionType: 'UPDATE_RECORD',
        parameters: { stage: 'IN_REVIEW', priority: 'HIGH' },
        executionMethod: 'API',
        timeoutMs: 20000,
      },
      {
        id: 'step_6',
        stepIndex: 6,
        name: 'Broadcast Operations Alert',
        type: 'ACTION',
        application: 'Slack',
        actionType: 'SEND_NOTIFICATION',
        parameters: { channel: '#customer-operations', mentionRole: '@support-leads' },
        executionMethod: 'API',
        timeoutMs: 10000,
      },
    ],
  },
  {
    id: 'wf_lead_dispatch',
    userId: DEMO_USER_ID,
    candidateId: 'cand_lead_notify',
    name: 'New Lead Ingestion & Dispatch',
    description: 'Instant notification and CRM routing for high-intent MQL leads.',
    category: 'Sales & Growth',
    version: 2,
    status: 'ACTIVE',
    createdAt: '2026-09-23T15:30:00.000Z',
    updatedAt: '2026-09-25T11:00:00.000Z',
    lastRunAt: '2026-09-25T20:15:00.000Z',
    totalExecutions: 24,
    successRate: 100.0,
    trigger: {
      id: 'trig_02',
      type: 'WEBHOOK_EVENT',
      application: 'HubSpot CRM',
      description: 'Trigger when lead score crosses 80 points',
      config: { event: 'contact.created', minScore: 80 },
    },
    variables: [
      { name: 'leadName', type: 'string' },
      { name: 'company', type: 'string' },
      { name: 'leadScore', type: 'number' },
    ],
    conditions: [],
    steps: [
      {
        id: 'step_l1',
        stepIndex: 1,
        name: 'Enrich Lead Company Profile',
        type: 'ACTION',
        application: 'Chrome',
        actionType: 'BROWSER_ENRICH_DOMAIN',
        parameters: { enrichEngine: 'SemanticCompanyLookup' },
        executionMethod: 'BROWSER_AUTOMATION',
        timeoutMs: 30000,
      },
      {
        id: 'step_l2',
        stepIndex: 2,
        name: 'Assign Account Executive',
        type: 'ACTION',
        application: 'HubSpot CRM',
        actionType: 'ASSIGN_OWNER',
        parameters: { rotationGroup: 'Enterprise-NorthAmerica' },
        executionMethod: 'API',
        timeoutMs: 15000,
      },
      {
        id: 'step_l3',
        stepIndex: 3,
        name: 'Dispatch Urgent Lead Alert',
        type: 'ACTION',
        application: 'Slack',
        actionType: 'SEND_RICH_BLOCK',
        parameters: { channel: '#sales-leads', notifyUrgent: true },
        executionMethod: 'API',
        timeoutMs: 10000,
      },
    ],
  },
  {
    id: 'wf_invoice_sync',
    userId: DEMO_USER_ID,
    candidateId: 'cand_invoice_sync',
    name: 'Weekly Invoice Ledger Sync',
    description: 'Extracts weekly billing files, reconciles line items with bank statements, and updates Google Sheets ledger.',
    category: 'Finance & Accounting',
    version: 1,
    status: 'PENDING_APPROVAL',
    createdAt: '2026-09-25T11:30:00.000Z',
    updatedAt: '2026-09-25T11:30:00.000Z',
    trigger: {
      id: 'trig_03',
      type: 'SCHEDULED_CRON',
      application: 'Google Sheets',
      description: 'Every Monday morning at 08:00 AM UTC',
      config: { cron: '0 8 * * 1' },
    },
    variables: [],
    conditions: [],
    steps: [
      {
        id: 'step_inv1',
        stepIndex: 1,
        name: 'Fetch Stripe Settlement Export',
        type: 'ACTION',
        application: 'Chrome',
        actionType: 'AUTOMATED_PORTAL_EXPORT',
        parameters: { portal: 'Stripe Dashboard', reportType: 'settlement_payouts' },
        executionMethod: 'BROWSER_AUTOMATION',
        timeoutMs: 45000,
      },
      {
        id: 'step_inv2',
        stepIndex: 2,
        name: 'Validate Tax Calculations',
        type: 'CONDITION',
        application: 'Google Sheets',
        actionType: 'CHECK_TAX_INTEGRITY',
        parameters: { varianceThresholdPct: 0.01 },
        executionMethod: 'API',
        timeoutMs: 10000,
      },
      {
        id: 'step_inv3',
        stepIndex: 3,
        name: 'Append Ledger Records',
        type: 'ACTION',
        application: 'Google Sheets',
        actionType: 'BATCH_APPEND_ROWS',
        parameters: { targetSheet: 'Q3 Financial Ledger' },
        executionMethod: 'API',
        timeoutMs: 25000,
      },
      {
        id: 'step_inv4',
        stepIndex: 4,
        name: 'Financial Controller Sign-off',
        type: 'HUMAN_APPROVAL',
        application: 'System',
        actionType: 'WAIT_FOR_APPROVAL',
        parameters: { reviewerRole: 'FINANCE_DIRECTOR', autoRejectTimeoutHours: 24 },
        executionMethod: 'APPLICATION',
        timeoutMs: 86400000,
        requiresApprovalPrompt: 'Review weekly invoice sync: 42 records processed totaling $124,850. Confirm ledger commit?',
      },
    ],
  },
  {
    id: 'wf_refund_triage',
    userId: DEMO_USER_ID,
    candidateId: 'cand_refund_triage',
    name: 'Customer Refund Triaging & Approval',
    description: 'Human-in-the-loop workflow for high-value customer refunds requiring automated verification and manager approval.',
    category: 'Customer Operations',
    version: 1,
    status: 'DRAFT',
    createdAt: '2026-09-25T16:20:00.000Z',
    updatedAt: '2026-09-25T16:20:00.000Z',
    trigger: {
      id: 'trig_04',
      type: 'EMAIL_RECEIVED',
      application: 'Gmail',
      description: 'Email received with subject keyword "Refund"',
      config: { query: 'subject:refund' },
    },
    variables: [{ name: 'refundAmount', type: 'number', defaultValue: '350.00' }],
    conditions: [{ id: 'cond_rf_01', field: 'refundAmount', operator: 'GREATER_THAN', value: 200 }],
    steps: [
      {
        id: 'step_rf1',
        stepIndex: 1,
        name: 'Verify Order ID in Payment Gateway',
        type: 'ACTION',
        application: 'Chrome',
        actionType: 'BROWSER_LOOKUP',
        parameters: { url: 'https://gateway.internal.net/charges' },
        executionMethod: 'BROWSER_AUTOMATION',
        timeoutMs: 30000,
      },
      {
        id: 'step_rf2',
        stepIndex: 2,
        name: 'Human Manager Approval',
        type: 'HUMAN_APPROVAL',
        application: 'System',
        actionType: 'WAIT_FOR_APPROVAL',
        parameters: { approver: 'support-manager@enterprise.com' },
        executionMethod: 'APPLICATION',
        timeoutMs: 3600000,
        requiresApprovalPrompt: 'Approve refund of $350.00 for Acme Corp (Transaction #TX-98402)?',
      },
      {
        id: 'step_rf3',
        stepIndex: 3,
        name: 'Apply Refund via Gateway',
        type: 'ACTION',
        application: 'Chrome',
        actionType: 'EXECUTE_REFUND',
        parameters: { reason: 'Customer Satisfaction' },
        executionMethod: 'BROWSER_AUTOMATION',
        timeoutMs: 30000,
      },
    ],
  },
  {
    id: 'wf_slack_daily_brief',
    userId: DEMO_USER_ID,
    name: 'Executive Daily Operations Briefing',
    description: 'Aggregates open CRM tickets, unread support emails, and ledger metrics into an 08:30 AM executive briefing.',
    category: 'Executive Insights',
    version: 1,
    status: 'PAUSED',
    createdAt: '2026-09-20T10:00:00.000Z',
    updatedAt: '2026-09-24T18:00:00.000Z',
    trigger: {
      id: 'trig_05',
      type: 'SCHEDULED_CRON',
      application: 'Slack',
      description: 'Daily at 08:30 AM weekdays',
      config: { cron: '30 8 * * 1-5' },
    },
    variables: [],
    conditions: [],
    steps: [
      {
        id: 'step_db1',
        stepIndex: 1,
        name: 'Count Pending Tickets',
        type: 'ACTION',
        application: 'HubSpot CRM',
        actionType: 'AGGREGATE_METRICS',
        parameters: { query: 'status:OPEN' },
        executionMethod: 'API',
        timeoutMs: 15000,
      },
      {
        id: 'step_db2',
        stepIndex: 2,
        name: 'Post Briefing to Executive Channel',
        type: 'ACTION',
        application: 'Slack',
        actionType: 'POST_EXECUTIVE_SUMMARY',
        parameters: { channel: '#leadership-digest' },
        executionMethod: 'API',
        timeoutMs: 10000,
      },
    ],
  },
];

export const INITIAL_AUTOMATIONS: Automation[] = [
  {
    id: 'auto_cust_req',
    userId: DEMO_USER_ID,
    workflowId: 'wf_process_cust_req',
    name: 'Customer Request Auto-Pilot',
    triggerType: 'EVENT_BASED',
    status: 'ACTIVE',
    totalRuns: 16,
    successfulRuns: 15,
    failedRuns: 1,
    lastRunAt: '2026-09-25T21:40:00.000Z',
    timeSavedSeconds: 15 * 384, // ~96 mins saved
  },
  {
    id: 'auto_lead_dispatch',
    userId: DEMO_USER_ID,
    workflowId: 'wf_lead_dispatch',
    name: 'MQL Lead Real-Time Router',
    triggerType: 'EVENT_BASED',
    status: 'ACTIVE',
    totalRuns: 24,
    successfulRuns: 24,
    failedRuns: 0,
    lastRunAt: '2026-09-25T20:15:00.000Z',
    timeSavedSeconds: 24 * 180, // ~72 mins saved
  },
  {
    id: 'auto_invoice_cron',
    userId: DEMO_USER_ID,
    workflowId: 'wf_invoice_sync',
    name: 'Weekly Financial Reconciliation',
    triggerType: 'SCHEDULED',
    scheduleCron: '0 8 * * 1',
    status: 'PAUSED',
    totalRuns: 3,
    successfulRuns: 3,
    failedRuns: 0,
    lastRunAt: '2026-09-22T08:00:00.000Z',
    timeSavedSeconds: 3 * 420,
  },
];

export function generateSeedExecutions(): Execution[] {
  const executions: Execution[] = [];
  const baseDate = new Date('2026-09-25T23:00:00.000Z');

  // Execution 1: Currently WAITING for human approval!
  executions.push({
    id: 'exec_approval_pending_01',
    userId: DEMO_USER_ID,
    workflowId: 'wf_refund_triage',
    workflowName: 'Customer Refund Triaging & Approval',
    status: 'WAITING',
    startTime: new Date(baseDate.getTime() - 8 * 60 * 1000).toISOString(),
    durationMs: 480000,
    triggerData: { emailSender: 'billing@globex.corp', refundAmount: 350.0 },
    inputs: { orderId: 'ORD-99124', reason: 'Billing dispute overage' },
    outputs: { orderValidated: true, originalChargeDate: '2026-09-10' },
    errors: [],
    timeSavedSeconds: 240,
    currentStepIndex: 2,
    isWaitingApproval: true,
    approvalPayload: {
      prompt: 'WorkFlowOS needs your approval: Process customer refund of $350.00 for Globex Corp (Order ORD-99124)?',
      stepIndex: 2,
      stepId: 'step_rf2',
      details: {
        customer: 'Globex Corp (billing@globex.corp)',
        amount: '$350.00',
        orderId: 'ORD-99124',
        riskScore: 'Low (Account in good standing 3+ years)',
      },
    },
    steps: [
      {
        id: 'es_appr_1',
        executionId: 'exec_approval_pending_01',
        stepId: 'step_rf1',
        stepIndex: 1,
        stepName: 'Verify Order ID in Payment Gateway',
        application: 'Chrome',
        executionMethod: 'BROWSER_AUTOMATION',
        status: 'SUCCESS',
        startTime: new Date(baseDate.getTime() - 8 * 60 * 1000).toISOString(),
        endTime: new Date(baseDate.getTime() - 7 * 60 * 1000).toISOString(),
        durationMs: 4200,
        inputData: { orderId: 'ORD-99124' },
        outputData: { chargeFound: true, amount: 350.0 },
        retryCount: 0,
      },
      {
        id: 'es_appr_2',
        executionId: 'exec_approval_pending_01',
        stepId: 'step_rf2',
        stepIndex: 2,
        stepName: 'Human Manager Approval',
        application: 'System',
        executionMethod: 'APPLICATION',
        status: 'WAITING_APPROVAL',
        startTime: new Date(baseDate.getTime() - 7 * 60 * 1000).toISOString(),
        inputData: { prompt: 'Process customer refund of $350.00 for Globex Corp?' },
        retryCount: 0,
      },
      {
        id: 'es_appr_3',
        executionId: 'exec_approval_pending_01',
        stepId: 'step_rf3',
        stepIndex: 3,
        stepName: 'Apply Refund via Gateway',
        application: 'Chrome',
        executionMethod: 'BROWSER_AUTOMATION',
        status: 'PENDING',
        retryCount: 0,
      },
    ],
  });

  // Execution 2: One FAILED execution with a realistic error: "Customer record could not be found in CRM"
  executions.push({
    id: 'exec_failed_02',
    userId: DEMO_USER_ID,
    workflowId: 'wf_process_cust_req',
    workflowName: 'Process Customer Request',
    automationId: 'auto_cust_req',
    status: 'FAILED',
    startTime: new Date(baseDate.getTime() - 45 * 60 * 1000).toISOString(),
    endTime: new Date(baseDate.getTime() - 44 * 60 * 1000).toISOString(),
    durationMs: 62400,
    triggerData: { sender: 'unregistered.guest@example.org', subject: 'Invoice Query' },
    inputs: { senderEmail: 'unregistered.guest@example.org' },
    outputs: { emailParsed: true, attachmentsFound: 1 },
    errors: ['Customer record could not be found in HubSpot CRM (Search by email returned 0 records)'],
    timeSavedSeconds: 120,
    currentStepIndex: 3,
    steps: [
      {
        id: 'es_f1',
        executionId: 'exec_failed_02',
        stepId: 'step_1',
        stepIndex: 1,
        stepName: 'Extract Customer Information',
        application: 'Gmail',
        executionMethod: 'API',
        status: 'SUCCESS',
        durationMs: 1420,
        inputData: { emailId: 'msg_9841' },
        outputData: { sender: 'unregistered.guest@example.org', subject: 'Invoice Query' },
        retryCount: 0,
      },
      {
        id: 'es_f2',
        executionId: 'exec_failed_02',
        stepId: 'step_2',
        stepIndex: 2,
        stepName: 'Download & Scan Attachment',
        application: 'Gmail',
        executionMethod: 'API',
        status: 'SUCCESS',
        durationMs: 3100,
        inputData: { attachment: 'invoice_query.pdf' },
        outputData: { sizeBytes: 104200, virusScan: 'CLEAN' },
        retryCount: 0,
      },
      {
        id: 'es_f3',
        executionId: 'exec_failed_02',
        stepId: 'step_3',
        stepIndex: 3,
        stepName: 'Search Customer in HubSpot CRM',
        application: 'HubSpot CRM',
        executionMethod: 'API',
        status: 'FAILED',
        durationMs: 2800,
        inputData: { email: 'unregistered.guest@example.org' },
        errorDetails: 'Customer record could not be found in HubSpot CRM (HTTP 404: Contact not found)',
        retryCount: 1,
      },
      {
        id: 'es_f4',
        executionId: 'exec_failed_02',
        stepId: 'step_4',
        stepIndex: 4,
        stepName: 'Verify Account Active Status',
        application: 'HubSpot CRM',
        executionMethod: 'API',
        status: 'SKIPPED',
        retryCount: 0,
      },
      {
        id: 'es_f5',
        executionId: 'exec_failed_02',
        stepId: 'step_5',
        stepIndex: 5,
        stepName: 'Update Customer Ticket Details',
        application: 'HubSpot CRM',
        executionMethod: 'API',
        status: 'SKIPPED',
        retryCount: 0,
      },
      {
        id: 'es_f6',
        executionId: 'exec_failed_02',
        stepId: 'step_6',
        stepIndex: 6,
        stepName: 'Broadcast Operations Alert',
        application: 'Slack',
        executionMethod: 'API',
        status: 'SKIPPED',
        retryCount: 0,
      },
    ],
  });

  // Generate 20+ successful realistic historical executions across the past 7 days
  const sampleCompanies = [
    'Acme International',
    'TechNova Systems',
    'Starlight Analytics',
    'Hyperion Global',
    'Apex Logistics',
    'Nexus Health',
    'Vanguard Media',
    'BlueWave Retail',
    'Zenith Cloud',
    'Orion Robotics',
  ];

  for (let i = 1; i <= 22; i++) {
    const minsAgo = i * 280 + Math.floor(Math.random() * 60);
    const execStart = new Date(baseDate.getTime() - minsAgo * 60 * 1000);
    const duration = Math.floor(1800 + Math.random() * 2400);
    const execEnd = new Date(execStart.getTime() + duration);
    const company = sampleCompanies[i % sampleCompanies.length];
    const isLeadFlow = i % 2 === 0;

    if (isLeadFlow) {
      executions.push({
        id: `exec_lead_${i}`,
        userId: DEMO_USER_ID,
        workflowId: 'wf_lead_dispatch',
        workflowName: 'New Lead Ingestion & Dispatch',
        automationId: 'auto_lead_dispatch',
        status: 'SUCCESS',
        startTime: execStart.toISOString(),
        endTime: execEnd.toISOString(),
        durationMs: duration,
        triggerData: { contact: `director@${company.toLowerCase().replace(/\s+/g, '')}.com`, score: 85 + (i % 15) },
        inputs: { companyName: company, tier: 'Enterprise' },
        outputs: { assignedOwner: 'Alex Morgan', slackMessageTs: `1727289${i}.0012` },
        errors: [],
        timeSavedSeconds: 180,
        currentStepIndex: 3,
        steps: [
          {
            id: `es_l1_${i}`,
            executionId: `exec_lead_${i}`,
            stepId: 'step_l1',
            stepIndex: 1,
            stepName: 'Enrich Lead Company Profile',
            application: 'Chrome',
            executionMethod: 'BROWSER_AUTOMATION',
            status: 'SUCCESS',
            durationMs: 1400,
            outputData: { employees: '250-500', industry: 'SaaS' },
            retryCount: 0,
          },
          {
            id: `es_l2_${i}`,
            executionId: `exec_lead_${i}`,
            stepId: 'step_l2',
            stepIndex: 2,
            stepName: 'Assign Account Executive',
            application: 'HubSpot CRM',
            executionMethod: 'API',
            status: 'SUCCESS',
            durationMs: 820,
            outputData: { owner: 'Alex Morgan' },
            retryCount: 0,
          },
          {
            id: `es_l3_${i}`,
            executionId: `exec_lead_${i}`,
            stepId: 'step_l3',
            stepIndex: 3,
            stepName: 'Dispatch Urgent Lead Alert',
            application: 'Slack',
            executionMethod: 'API',
            status: 'SUCCESS',
            durationMs: 510,
            outputData: { channel: '#sales-leads', delivered: true },
            retryCount: 0,
          },
        ],
      });
    } else {
      executions.push({
        id: `exec_cust_${i}`,
        userId: DEMO_USER_ID,
        workflowId: 'wf_process_cust_req',
        workflowName: 'Process Customer Request',
        automationId: 'auto_cust_req',
        status: 'SUCCESS',
        startTime: execStart.toISOString(),
        endTime: execEnd.toISOString(),
        durationMs: duration + 1200,
        triggerData: { emailSender: `support@${company.toLowerCase().replace(/\s+/g, '')}.com`, ticketId: `TCK-${8400 + i}` },
        inputs: { customerCompany: company },
        outputs: { crmUpdated: true, notificationDelivered: true },
        errors: [],
        timeSavedSeconds: 384,
        currentStepIndex: 6,
        steps: [
          {
            id: `es_c1_${i}`,
            executionId: `exec_cust_${i}`,
            stepId: 'step_1',
            stepIndex: 1,
            stepName: 'Extract Customer Information',
            application: 'Gmail',
            executionMethod: 'API',
            status: 'SUCCESS',
            durationMs: 1100,
            retryCount: 0,
          },
          {
            id: `es_c2_${i}`,
            executionId: `exec_cust_${i}`,
            stepId: 'step_2',
            stepIndex: 2,
            stepName: 'Download & Scan Attachment',
            application: 'Gmail',
            executionMethod: 'API',
            status: 'SUCCESS',
            durationMs: 1900,
            retryCount: 0,
          },
          {
            id: `es_c3_${i}`,
            executionId: `exec_cust_${i}`,
            stepId: 'step_3',
            stepIndex: 3,
            stepName: 'Search Customer in HubSpot CRM',
            application: 'HubSpot CRM',
            executionMethod: 'API',
            status: 'SUCCESS',
            durationMs: 950,
            retryCount: 0,
          },
          {
            id: `es_c4_${i}`,
            executionId: `exec_cust_${i}`,
            stepId: 'step_4',
            stepIndex: 4,
            stepName: 'Verify Account Active Status',
            application: 'HubSpot CRM',
            executionMethod: 'API',
            status: 'SUCCESS',
            durationMs: 400,
            retryCount: 0,
          },
          {
            id: `es_c5_${i}`,
            executionId: `exec_cust_${i}`,
            stepId: 'step_5',
            stepIndex: 5,
            stepName: 'Update Customer Ticket Details',
            application: 'HubSpot CRM',
            executionMethod: 'API',
            status: 'SUCCESS',
            durationMs: 1200,
            retryCount: 0,
          },
          {
            id: `es_c6_${i}`,
            executionId: `exec_cust_${i}`,
            stepId: 'step_6',
            stepIndex: 6,
            stepName: 'Broadcast Operations Alert',
            application: 'Slack',
            executionMethod: 'API',
            status: 'SUCCESS',
            durationMs: 620,
            retryCount: 0,
          },
        ],
      });
    }
  }

  return executions;
}

export function generateSeedActivityEvents(): ActivityEvent[] {
  const events: ActivityEvent[] = [];
  const baseTime = new Date('2026-09-25T23:15:00.000Z').getTime();

  // Create 10+ distinct activity sessions simulating user work
  const sessions = [
    {
      id: 'sess_101',
      title: 'Customer Inquiry Handling',
      steps: [
        { app: 'Chrome' as const, type: 'APPLICATION_OPENED' as const, action: 'Launch Chrome browser', target: 'Desktop' },
        { app: 'Gmail' as const, type: 'EMAIL_OPENED' as const, action: 'Opened customer email', target: 'Subject: Urgent Renewal Question' },
        { app: 'Gmail' as const, type: 'EMAIL_ATTACHMENT_DOWNLOADED' as const, action: 'Attachment downloaded', target: 'contract_renewal_signed.pdf' },
        { app: 'HubSpot CRM' as const, type: 'CRM_RECORD_SEARCHED' as const, action: 'Customer searched', target: 'Acme Corp contact search' },
        { app: 'HubSpot CRM' as const, type: 'CRM_RECORD_UPDATED' as const, action: 'Customer record updated', target: 'Stage changed to Closed Won' },
        { app: 'Slack' as const, type: 'MESSAGE_SENT' as const, action: 'Message sent', target: '#customer-operations' },
      ],
    },
    {
      id: 'sess_102',
      title: 'Customer Inquiry Handling (Repeat 2)',
      steps: [
        { app: 'Gmail' as const, type: 'EMAIL_OPENED' as const, action: 'Opened customer email', target: 'Subject: License Upgrade Invoice' },
        { app: 'Gmail' as const, type: 'EMAIL_ATTACHMENT_DOWNLOADED' as const, action: 'Attachment downloaded', target: 'po_order_9984.pdf' },
        { app: 'HubSpot CRM' as const, type: 'CRM_RECORD_SEARCHED' as const, action: 'Customer searched', target: 'TechNova contact search' },
        { app: 'HubSpot CRM' as const, type: 'CRM_RECORD_UPDATED' as const, action: 'Customer record updated', target: 'Updated license tier' },
        { app: 'Slack' as const, type: 'MESSAGE_SENT' as const, action: 'Message sent', target: '#customer-operations' },
      ],
    },
    {
      id: 'sess_103',
      title: 'Customer Inquiry Handling (Repeat 3)',
      steps: [
        { app: 'Gmail' as const, type: 'EMAIL_OPENED' as const, action: 'Opened customer email', target: 'Subject: Requesting revised statement' },
        { app: 'Gmail' as const, type: 'EMAIL_ATTACHMENT_DOWNLOADED' as const, action: 'Attachment downloaded', target: 'billing_statement.pdf' },
        { app: 'HubSpot CRM' as const, type: 'CRM_RECORD_SEARCHED' as const, action: 'Customer searched', target: 'BlueWave contact search' },
        { app: 'HubSpot CRM' as const, type: 'CRM_RECORD_UPDATED' as const, action: 'Customer record updated', target: 'Account flagged for statement review' },
        { app: 'Slack' as const, type: 'MESSAGE_SENT' as const, action: 'Message sent', target: '#customer-operations' },
      ],
    },
    {
      id: 'sess_104',
      title: 'Inbound Lead Qualification',
      steps: [
        { app: 'HubSpot CRM' as const, type: 'CRM_RECORD_SEARCHED' as const, action: 'Filter high score leads', target: 'New MQL submissions' },
        { app: 'HubSpot CRM' as const, type: 'CRM_RECORD_UPDATED' as const, action: 'Assign owner', target: 'Assigned to Alex Morgan' },
        { app: 'Slack' as const, type: 'MESSAGE_SENT' as const, action: 'Message sent', target: '#sales-leads' },
      ],
    },
    {
      id: 'sess_105',
      title: 'Inbound Lead Qualification (Repeat 2)',
      steps: [
        { app: 'HubSpot CRM' as const, type: 'CRM_RECORD_SEARCHED' as const, action: 'Filter high score leads', target: 'Enterprise demo requests' },
        { app: 'HubSpot CRM' as const, type: 'CRM_RECORD_UPDATED' as const, action: 'Assign owner', target: 'Assigned to Jordan Taylor' },
        { app: 'Slack' as const, type: 'MESSAGE_SENT' as const, action: 'Message sent', target: '#sales-leads' },
      ],
    },
    {
      id: 'sess_106',
      title: 'Billing Report Export & Ledger Sync',
      steps: [
        { app: 'Chrome' as const, type: 'DATA_EXPORTED' as const, action: 'Export payment report CSV', target: 'Stripe Settlement Table' },
        { app: 'Desktop Files' as const, type: 'FILE_CREATED' as const, action: 'Read downloaded CSV', target: 'payouts_week_38.csv' },
        { app: 'Google Sheets' as const, type: 'SPREADSHEET_ROW_ADDED' as const, action: 'Append row to Q3 Ledger', target: 'Financial Ledger Sheet' },
      ],
    },
    {
      id: 'sess_107',
      title: 'Billing Report Export & Ledger Sync (Repeat 2)',
      steps: [
        { app: 'Chrome' as const, type: 'DATA_EXPORTED' as const, action: 'Export payment report CSV', target: 'Stripe Settlement Table' },
        { app: 'Desktop Files' as const, type: 'FILE_CREATED' as const, action: 'Read downloaded CSV', target: 'payouts_week_39.csv' },
        { app: 'Google Sheets' as const, type: 'SPREADSHEET_ROW_ADDED' as const, action: 'Append row to Q3 Ledger', target: 'Financial Ledger Sheet' },
      ],
    },
    {
      id: 'sess_108',
      title: 'Support Ticket Triage',
      steps: [
        { app: 'Gmail' as const, type: 'EMAIL_OPENED' as const, action: 'Opened customer email', target: 'Subject: Issue accessing API key' },
        { app: 'HubSpot CRM' as const, type: 'CRM_RECORD_SEARCHED' as const, action: 'Search account API tier', target: 'Developer Portal' },
        { app: 'Slack' as const, type: 'MESSAGE_SENT' as const, action: 'Message sent', target: '#api-support' },
      ],
    },
    {
      id: 'sess_109',
      title: 'Customer Inquiry Handling (Repeat 4)',
      steps: [
        { app: 'Gmail' as const, type: 'EMAIL_OPENED' as const, action: 'Opened customer email', target: 'Subject: Enterprise SLA Questions' },
        { app: 'Gmail' as const, type: 'EMAIL_ATTACHMENT_DOWNLOADED' as const, action: 'Attachment downloaded', target: 'sla_addendum.pdf' },
        { app: 'HubSpot CRM' as const, type: 'CRM_RECORD_SEARCHED' as const, action: 'Customer searched', target: 'Orion Robotics' },
        { app: 'HubSpot CRM' as const, type: 'CRM_RECORD_UPDATED' as const, action: 'Customer record updated', target: 'SLA Addendum Logged' },
        { app: 'Slack' as const, type: 'MESSAGE_SENT' as const, action: 'Message sent', target: '#customer-operations' },
      ],
    },
    {
      id: 'sess_110',
      title: 'Daily Slack Status Sync',
      steps: [
        { app: 'Google Sheets' as const, type: 'SPREADSHEET_ROW_ADDED' as const, action: 'Review daily targets', target: 'Q3 KPI Sheet' },
        { app: 'Slack' as const, type: 'MESSAGE_SENT' as const, action: 'Post morning summary', target: '#general' },
      ],
    },
  ];

  let eventCounter = 1;
  sessions.forEach((sess, sIdx) => {
    const sessionStartTime = baseTime - (sessions.length - sIdx) * 18 * 60 * 1000;
    sess.steps.forEach((step, stepIdx) => {
      const eventTime = new Date(sessionStartTime + stepIdx * 25 * 1000).toISOString();
      events.push({
        id: `evt_${eventCounter++}`,
        userId: DEMO_USER_ID,
        sessionId: sess.id,
        timestamp: eventTime,
        source: 'PROTOTYPE_SIMULATOR',
        application: step.app,
        eventType: step.type,
        action: step.action,
        target: step.target,
        metadata: {
          sessionTitle: sess.title,
          stepSequence: stepIdx + 1,
          clientVersion: 'WorkFlowOS-Prototype-v1.0.0',
        },
        isSimulated: true,
        sensitiveDataScrubbed: true,
      });
    });
  });

  return events;
}

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif_01',
    userId: DEMO_USER_ID,
    type: 'WORKFLOW_DISCOVERED',
    title: 'New Workflow Pattern Discovered',
    message: 'AI recognized "Process Customer Request" repeated 14 times with 94% pattern similarity.',
    link: '/discovery',
    read: false,
    createdAt: '2026-09-25T22:30:00.000Z',
  },
  {
    id: 'notif_02',
    userId: DEMO_USER_ID,
    type: 'APPROVAL_REQUIRED',
    title: 'Human Approval Required',
    message: 'Workflow "Customer Refund Triaging & Approval" is paused awaiting manager verification of $350.00.',
    link: '/executions',
    read: false,
    createdAt: '2026-09-25T23:05:00.000Z',
  },
  {
    id: 'notif_03',
    userId: DEMO_USER_ID,
    type: 'AUTOMATION_FAILED',
    title: 'Automation Execution Notice',
    message: 'Execution #exec_failed_02 stopped: Customer record not found in HubSpot CRM.',
    link: '/executions',
    read: true,
    createdAt: '2026-09-25T22:15:00.000Z',
  },
  {
    id: 'notif_04',
    userId: DEMO_USER_ID,
    type: 'WORKFLOW_APPROVED',
    title: 'Workflow Activated',
    message: '"New Lead Ingestion & Dispatch" was approved and deployed to automated runner.',
    link: '/workflows',
    read: true,
    createdAt: '2026-09-24T10:30:00.000Z',
  },
];
